-- market_snapshots 시드 SQL — scripts/build-market-snapshots-seed-sql.mjs 로 자동 생성
-- Supabase Dashboard → SQL Editor 에 붙여넣고 Run

-- 테이블이 없으면 만듦 (이미 migration 으로 만들었으면 noop)
create table if not exists public.market_snapshots (
  key text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);
alter table public.market_snapshots enable row level security;
grant select on public.market_snapshots to anon, authenticated;
drop policy if exists "Public can read market snapshots" on public.market_snapshots;
create policy "Public can read market snapshots"
  on public.market_snapshots for select to anon, authenticated using (true);

-- 7개 키 upsert (regional / monthly / area_type / top_urgent / insights / metadata / home_trend)
begin;
insert into public.market_snapshots (key, data) values ('regional', '[{"region":"경기","averageDealPrice":574794540,"averageDiscount":-4.2,"transactionVolume":11812,"urgentRatio":0.13},{"region":"서울","averageDealPrice":1067007903,"averageDiscount":-41.8,"transactionVolume":4701,"urgentRatio":0.08},{"region":"경상남","averageDealPrice":265692941,"averageDiscount":1.6,"transactionVolume":2404,"urgentRatio":0.16},{"region":"부산","averageDealPrice":415897269,"averageDiscount":-3.4,"transactionVolume":2380,"urgentRatio":0.12},{"region":"인천","averageDealPrice":406235472,"averageDiscount":-1.9,"transactionVolume":2330,"urgentRatio":0.14},{"region":"충청남","averageDealPrice":221845520,"averageDiscount":5.1,"transactionVolume":1692,"urgentRatio":0.18},{"region":"대구","averageDealPrice":370204612,"averageDiscount":0.5,"transactionVolume":1509,"urgentRatio":0.1},{"region":"경상북","averageDealPrice":194189878,"averageDiscount":5.3,"transactionVolume":1472,"urgentRatio":0.16},{"region":"충청북","averageDealPrice":260003778,"averageDiscount":1.5,"transactionVolume":1416,"urgentRatio":0.17},{"region":"전북","averageDealPrice":234032432,"averageDiscount":5,"transactionVolume":1390,"urgentRatio":0.19},{"region":"강원","averageDealPrice":217255139,"averageDiscount":3.3,"transactionVolume":1220,"urgentRatio":0.2},{"region":"광주","averageDealPrice":297288716,"averageDiscount":1.2,"transactionVolume":1168,"urgentRatio":0.17},{"region":"울산","averageDealPrice":343687421,"averageDiscount":1.3,"transactionVolume":1043,"urgentRatio":0.12},{"region":"대전","averageDealPrice":359700817,"averageDiscount":0,"transactionVolume":1040,"urgentRatio":0.13},{"region":"전라남","averageDealPrice":205774831,"averageDiscount":9.5,"transactionVolume":1037,"urgentRatio":0.24},{"region":"세종","averageDealPrice":530296552,"averageDiscount":-0.7,"transactionVolume":348,"urgentRatio":0.06},{"region":"제주","averageDealPrice":350361538,"averageDiscount":-37.4,"transactionVolume":143,"urgentRatio":0.03}]'::jsonb)
on conflict (key) do update set data = excluded.data, updated_at = now();
insert into public.market_snapshots (key, data) values ('monthly', '[{"month":"2026-04","averageDealPrice":511773628,"averageDiscount":-6.3,"urgentCount":3363,"transactionVolume":24796},{"month":"2026-05","averageDealPrice":438445071,"averageDiscount":-3.5,"urgentCount":1700,"transactionVolume":12309}]'::jsonb)
on conflict (key) do update set data = excluded.data, updated_at = now();
insert into public.market_snapshots (key, data) values ('area_type', '[{"bucket":"60㎡ 이하","averageDealPrice":350373372,"averageDiscount":-6.7,"transactionVolume":14750},{"bucket":"60–85㎡","averageDealPrice":515245944,"averageDiscount":-4.5,"transactionVolume":18190},{"bucket":"85–102㎡","averageDealPrice":757549385,"averageDiscount":-0.5,"transactionVolume":1105},{"bucket":"102–135㎡","averageDealPrice":804372241,"averageDiscount":-3.8,"transactionVolume":2445},{"bucket":"135㎡ 초과","averageDealPrice":1207554634,"averageDiscount":-1.2,"transactionVolume":615}]'::jsonb)
on conflict (key) do update set data = excluded.data, updated_at = now();
insert into public.market_snapshots (key, data) values ('top_urgent', '[{"rank":1,"complex":"건영캐스빌","region":"서울특별시 중랑구 상봉동","dealCount":4,"sampleSize":9,"averageDiscount":31.7,"urgentRatio":0.44},{"rank":2,"complex":"미륭","region":"서울특별시 노원구 월계동","dealCount":3,"sampleSize":9,"averageDiscount":30.8,"urgentRatio":0.33},{"rank":3,"complex":"대한","region":"경상남도 창원시 의창구 동읍 신방리","dealCount":1,"sampleSize":5,"averageDiscount":26.2,"urgentRatio":0.2},{"rank":4,"complex":"베스티움","region":"부산광역시 남구 문현동","dealCount":2,"sampleSize":7,"averageDiscount":23.6,"urgentRatio":0.29},{"rank":5,"complex":"대동타운","region":"부산광역시 해운대구 좌동","dealCount":2,"sampleSize":8,"averageDiscount":22.7,"urgentRatio":0.25},{"rank":6,"complex":"매화","region":"전라남도 광양시 금호동","dealCount":1,"sampleSize":6,"averageDiscount":21.9,"urgentRatio":0.17},{"rank":7,"complex":"초원","region":"대전광역시 서구 만년동","dealCount":3,"sampleSize":6,"averageDiscount":21.1,"urgentRatio":0.5},{"rank":8,"complex":"상록","region":"강원특별자치도 원주시 태장동","dealCount":1,"sampleSize":5,"averageDiscount":19.1,"urgentRatio":0.2},{"rank":9,"complex":"현대그린","region":"서울특별시 서대문구 홍제동","dealCount":5,"sampleSize":12,"averageDiscount":19,"urgentRatio":0.42},{"rank":10,"complex":"해태","region":"전북특별자치도 순창군 순창읍 남계리","dealCount":1,"sampleSize":6,"averageDiscount":18.6,"urgentRatio":0.17}]'::jsonb)
on conflict (key) do update set data = excluded.data, updated_at = now();
insert into public.market_snapshots (key, data) values ('insights', '[{"label":"급매 비율","value":"13.6%","direction":"up","delta":"5,063건 / 37,105건","note":"단지·면적 median 대비 5%↑ 할인"},{"label":"급매 평균 할인율","value":"21.1%","direction":"up","delta":"중앙값 13.1%","note":"급매 거래만 집계"},{"label":"평균 거래가","value":"4억 8,744만","direction":"up","delta":"전체 거래 단순 평균","note":"단지별 가중 없음"},{"label":"집계 거래량","value":"37,105건","direction":"up","delta":"2026-04","note":"국토부 실거래 데이터"}]'::jsonb)
on conflict (key) do update set data = excluded.data, updated_at = now();
insert into public.market_snapshots (key, data) values ('metadata', '{"name":"국토교통부 실거래가 공개시스템","endpoint":"CSV 일괄 다운로드","lastUpdated":"2026-05-14","disclosureLag":"계약일 기준 약 2주 후 공개","totalRows":37105,"months":["2026-04","2026-05"]}'::jsonb)
on conflict (key) do update set data = excluded.data, updated_at = now();
insert into public.market_snapshots (key, data) values ('home_trend', '[{"month":"12월","averageDiscount":5.6,"urgentCount":42,"transactionVolume":121},{"month":"1월","averageDiscount":5.9,"urgentCount":47,"transactionVolume":118},{"month":"2월","averageDiscount":6.4,"urgentCount":53,"transactionVolume":112},{"month":"3월","averageDiscount":6.8,"urgentCount":61,"transactionVolume":109},{"month":"4월","averageDiscount":7.3,"urgentCount":68,"transactionVolume":104},{"month":"5월","averageDiscount":7.8,"urgentCount":76,"transactionVolume":99}]'::jsonb)
on conflict (key) do update set data = excluded.data, updated_at = now();
commit;
